name: Run Notebook on Paperspace

on:
  workflow_dispatch:
    inputs:
      notebookPath:
        description: 'Path to notebook in repo (not used in SDK script)'
        required: true
        default: 'notebooks/hello_world.ipynb'
      projectId:
        description: 'Paperspace Project ID (not used in SDK script)'
        required: true
        default: 'pauavo5rvcp'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Gradient SDK
        run: pip install gradient

      - name: Run notebook script
        env:
          PAPERSPACE_API_KEY: ${{ secrets.PAPERSPACE_API_KEY }}
          PAPERSPACE_NOTEBOOK_ID: rrzklo2qdq71q14
        run: python scripts/run_notebook.py
