name: Run Notebook via Paperspace SDK

on:
  workflow_dispatch:
    inputs:
      notebookPath:
        description: 'Notebook path in repo'
        required: true
        default: 'notebooks/hello_world.ipynb'
      projectId:
        description: 'Paperspace Project ID'
        required: true
        default: 'pauavo5rvcp'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gradient-sdk papermill

      - name: Run notebook on Paperspace using SDK
        env:
          PS_API_KEY: ${{ secrets.PAPERSPACE_API_KEY }}
          NOTEBOOK_PATH: ${{ github.event.inputs.notebookPath }}
          PROJECT_ID: ${{ github.event.inputs.projectId }}
        run: |
          python .github/scripts/run_notebook.py
