name: Run Hello World on Paperspace

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install papermill
        run: pip install papermill

      - name: Install gradient CLI
        run: npm install -g @paperspace/gradient-cli

      - name: Authenticate with Paperspace
        run: gradient login --key ${{ secrets.PAPERSPACE_API_KEY }}

      - name: Submit job to Paperspace
        run: |
          gradient jobs create \
            --projectId YOUR_PROJECT_ID \
            --machineType C6 \
            --container python:3.9 \
            --workspace "." \
            --command "pip install papermill && papermill notebooks/hello_world.ipynb output.ipynb"
